version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): "
      include: "scope"

  # Enable version updates for R packages (if we had renv.lock)
  # Uncomment if you add renv dependency management
  # - package-ecosystem: "r"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   commit-message:
  #     prefix: "chore(deps): "
  #     include: "scope" 